name: Python Package using Conda
on: [push]

jobs:
  test:
    name: Test python ${{ matrix.python-version }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v2
      - name: install mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          use-only-tar-bz2: true
          miniforge-version: latest
          environment-file: GP.yml
          environment-name: GP
      - name: Install test packages
        shell: bash -l {0}
        run: |
          pip install pytest nbconvert nbformat
      - name: which python
        shell: bash -l {0}
        run: |
          which python
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pytest .github/workflows/test_notebooks.py
